#!/usr/bin/env bash

SCALA_VERSION=2.10.2

# Figure out where the Scala framework is installed
FWDIR="$(cd `dirname $0`; pwd)"

# Export this as PROJECT_HOME
export PROJECT_HOME="$FWDIR"

# Find the java binary
if [ -n "${JAVA_HOME}" ]; then
  RUNNER="${JAVA_HOME}/bin/java"
else
  if [ `command -v java` ]; then
    RUNNER="java"
  else
    echo "JAVA_HOME is not set" >&2
    exit 1
  fi
fi

# Compute classpath using external script
CLASSPATH="$FWDIR/target/scala-2.10/classes"
CLASSPATH="/root/.sbt/boot/scala-2.10.2/lib/scala-library.jar:$CLASSPATH"
#CLASSPATH="/root/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.2.3.jar:$CLASSPATH"
#CLASSPATH="/root/.ivy2/cache/com.typesafe/config/bundles/config-1.0.2.jar:$CLASSPATH"
export CLASSPATH

exec "$RUNNER" -cp "$CLASSPATH" $JAVA_OPTS "$@"
